Bookwise/Models/TeachersCorner.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachersCorner
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string SchoolName { get; set; }
        public string SchoolAddress { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}

Bookwise/Controllers/TeachersCornerController.cs
using BookWise.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookWise.Controllers
{
    public class TeachersCornerController : Controller
    {
        // GET: TeachersCorner
        public ActionResult ScienceWorld()
        {
            return View();
        }

        public ActionResult Grammar()
        {
            return View();
        }

        //public ActionResult GrammarBook1()
        //{
        //    List<Books> BookPages = new List<Books>();
        //    using (BookWiseEntities db = new BookWiseEntities())
        //    {
        //        BookPages = db.Books.Where(x=> x.Category == "GrammarBook1").ToList();
        //    }
        //    return View(BookPages);
        //}

        //public ActionResult GrammarBook2()
        //{
        //    List<Books> BookPages = new List<Books>();
        //    using (BookWiseEntities db = new BookWiseEntities())
        //    {
        //        BookPages = db.Books.Where(x => x.Category == "GrammarBook2").ToList();
        //    }
        //    return View(BookPages);
        //}

        //public ActionResult GrammarBook3()
        //{
        //    List<Books> BookPages = new List<Books>();
        //    using (BookWiseEntities db = new BookWiseEntities())
        //    {
        //        BookPages = db.Books.Where(x => x.Category == "GrammarBook3").ToList();
        //    }
        //    return View(BookPages);
        //}

        //public ActionResult GrammarBook4()
        //{
        //    return View();
        //}

        //public ActionResult GrammarBook5()
        //{
        //    return View();
        //}

        //public ActionResult GrammarBook6()
        //{
        //    return View();
        //}

        //public ActionResult GrammarBook7()
        //{
        //    return View();
        //}

        //public ActionResult GrammarBook8()
        //{
        //    return View();
        //}

        public ActionResult RightClick()
        {
            return View();
        }

        //public ActionResult RightClickBook1()
        //{
        //    List<Books> BookPages = new List<Books>();
        //    using (BookWiseEntities db = new BookWiseEntities())
        //    {
        //        BookPages = db.Books.Where(x => x.Category == "RightClickBook1").ToList();
        //    }
        //    return View(BookPages);
        //}

        //public ActionResult RightClickBook2()
        //{
        //    List<Books> BookPages = new List<Books>();
        //    using (BookWiseEntities db = new BookWiseEntities())
        //    {
        //        BookPages = db.Books.Where(x => x.Category == "RightClickBook2").ToList();
        //    }
        //    return View(BookPages);
        //}

        //public ActionResult RightClickBook3()
        //{
        //    List<Books> BookPages = new List<Books>();
        //    using (BookWiseEntities db = new BookWiseEntities())
        //    {
        //        BookPages = db.Books.Where(x => x.Category == "RightClickBook3").ToList();
        //    }
        //    return View(BookPages);
        //}

        //public ActionResult RightClickBook4()
        //{
        //    return View();
        //}

        //public ActionResult RightClickBook5()
        //{
        //    return View();
        //}

        public ActionResult SocialStudies()
        {
            return View();
        }

        //public ActionResult SocialStudiesBook6()
        //{
        //    List<Books> BookPages = new List<Books>();
        //    using (BookWiseEntities db = new BookWiseEntities())
        //    {
        //        BookPages = db.Books.Where(x => x.Category == "SocialStudiesBook6").ToList();
        //    }
        //    return View(BookPages);
        //}

        //public ActionResult SocialStudiesBook7()
        //{
        //    List<Books> BookPages = new List<Books>();
        //    using (BookWiseEntities db = new BookWiseEntities())
        //    {
        //        BookPages = db.Books.Where(x => x.Category == "SocialStudiesBook7").ToList();
        //    }
        //    return View(BookPages);
        //}

        //public ActionResult SocialStudiesBook8()
        //{
        //    List<Books> BookPages = new List<Books>();
        //    using (BookWiseEntities db = new BookWiseEntities())
        //    {
        //        BookPages = db.Books.Where(x => x.Category == "SocialStudiesBook8").ToList();
        //    }
        //    return View(BookPages);
        //}

        //[HttpGet]
        //public ActionResult Login()
        //{
        //    return View();
        //}

        //[HttpPost]
        //public ActionResult Login(FormCollection fc)
        //{
        //    try
        //    {
        //        TeachersCorner tc = new TeachersCorner();
        //        using (BookWiseEntities dal = new BookWiseEntities())
        //        {
        //            string username = fc["Username"];
        //            string password = fc["Password"];

        //            tc = (from t in dal.TeachersCorner where t.Username == username && t.Password == password select t).FirstOrDefault();
        //            if (tc != null)
        //            {
        //                Session["Teacher"] = tc;
        //                return RedirectToAction("Teachers", "TeachersCorner");
        //            }
        //            else
        //            {
        //                TempData["Color"] = "red";
        //                TempData["Message"] = "Provided username and password is incorrect. Contact BookWise Administrator!";
        //                TempData.Keep("Color");
        //                TempData.Keep("Message");
        //                return RedirectToAction("Login", "TeachersCorner");
        //            }
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        TempData["Color"] = "red";
        //        TempData["Message"] = "Sorry for the inconvenience. Please try again later!";
        //        TempData.Keep("Color");
        //        TempData.Keep("Message");
        //        return RedirectToAction("Login", "TeachersCorner");
        //    }
        //}

        //[HttpGet]
        //public ActionResult Teachers()
        //{
        //    if (Session["Teacher"] != null)
        //    {
        //        TeachersCorner tc = (TeachersCorner)Session["Teacher"];
        //        return View(tc);
        //    }
        //    else
        //    {
        //        return RedirectToAction("Index", "Home");
        //    }

        //}

        //[HttpGet]
        //public ActionResult Logout()
        //{
        //    Session.Abandon();
        //    return RedirectToAction("Index", "Home");
        //}
    }
}

Bookwise/Views/TeachersCorner/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>Index</h2>

Bookwise/Views/TeachersCorner/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<div class="container" style="margin-bottom:30px; margin-top:15px;">

    <div class="row">

        <div class="col-sm-6">
            <h3>Registered Teachers</h3>
            <p>Please login to continue...</p>

            @using (Html.BeginForm("Login", "TeachersCorner", FormMethod.Post, new { id = "teacherslogin", enctype = "multipart/form-data" }))
            {
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" style="color:red">Username</label>
                    <div class="col-sm-8">
                        <input required name="Username" type="text" class="form-control" placeholder="Type Username">
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" style="color:red">Password</label>
                    <div class="col-sm-8">
                        <input required name="Password" type="password" class="form-control" placeholder="Type Password">
                    </div>
                </div>

                <div style="margin-top:30px; margin-bottom:20px;">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label" style="color:red"></label>
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Login</button>
                            <button type="reset" class="btn btn-primary">Clear</button>
                        </div>
                    </div>
                </div>
            }
                @if (TempData["Message"] != null)
            {
                    <div style="color:@TempData["Color"]">
                        @TempData["Message"]
                    </div>
                    TempData["Color"] = null;
                    TempData["Message"] = null;
                }

        </div>
        <div class="col-sm-6">
            <h3>New Registration</h3>
            <p>
                Fill up the form to get complete access to teacher's handbooks.
            </p>
            @using (Html.BeginForm("TeachersCorner", "Admin", FormMethod.Post, new { id = "addproduct", enctype = "multipart/form-data" }))
            {
                <div class="form-group">
                    <div class="input-group col-xs-10">
                        @Html.TextBox("Name", null, new { @class = "form-control", placeholder = "Your Name", required = "required" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group col-xs-10">
                        @Html.TextBox("Email", null, new { @class = "form-control", placeholder = "Your Email", required = "required", Type = "Email" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group col-xs-10">
                        @Html.TextBox("Contact", null, new { @class = "form-control", placeholder = "Your Contact Number", required = "required" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group col-xs-10">
                        @Html.TextBox("SchoolName", null, new { @class = "form-control", placeholder = "School Name", required = "required" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group col-xs-10">
                        @Html.TextBox("SchoolAddress", null, new { @class = "form-control", placeholder = "School Address", required = "required" })
                    </div>
                </div>
                    <input type="hidden" name="Controller" value="Grammar" />
                    <div style="margin-top:30px; margin-bottom:20px;">
                        <div class="form-group">
                            <button class="btn btn-primary">
                                Register Now
                            </button>
                        </div>
                    </div>
            }
            <div>
                @if (TempData["Message"] != null)
            {
                    <div style="color:@TempData["Color"]">
                        @TempData["Message"]
                    </div>
                    TempData["Color"] = null;
                    TempData["Message"] = null;
                }
            </div>
        </div>
    </div>
</div>

Bookwise/Views/TeachersCorner/SocialStudies.cshtml
@{
    ViewBag.Title = "Social Studies";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<div class="page-content">
    <div class="container-fluid">
        <article id="post-74" class="post-74 page type-page status-publish hentry">
            <div class="vc_row wpb_row vc_row-fluid banner-box-left vc_custom_1490772168459 vc_column-gap-15">
            </div>
            <div class="vc_row wpb_row vc_row-fluid vc_column-gap-15">
                <div class="pull-right wpb_column vc_column_container vc_col-sm-8 vc_col-lg-9 vc_col-md-8">
                    <div class="vc_column-inner vc_custom_1498037949212">
                        <div class="wpb_wrapper">

                            <h3 style="font-size: 18px;text-align: left" class="vc_custom_heading custom-heading vc_custom_1490581250175">Teacher's Guide For Social Studies For Pakistan</h3>
                            <div class="shop-products grid-view row">

                                <div class="first vgw-items col-md-2 col-xs-6 post-207 product type-product status-publish has-post-thumbnail product_cat-arts-photography product_cat-audiobooks product_cat-biographies product_cat-business-money product_cat-bussiness-money product_cat-calendars product_cat-casual-shirts product_cat-childrens-books product_cat-chinos product_cat-comics product_cat-computers product_cat-cookbooks product_cat-dress-pants product_cat-education product_cat-limited-edition product_cat-mens product_cat-womens product_tag-tag1 product_tag-tag2 product_tag-tag3 product_tag-tag4 instock sale featured taxable shipping-taxable purchasable product-type-simple">

                                    <div class="vgw-item effect-3">
                                        <div class="list-col4">

                                            <div class="product-image">
                                                <a title="Social Studies Book 6">
                                                    <img width="200" height="280" src="~/Content/Mockups/TeachersCorner/SocialStudies/Social Studies Book 6.jpg" class="primary_image lazy wp-post-image" alt="Social Studies Book 6" /><span class="second"><img width="200" height="280" src="~/Content/Mockups/TeachersCorner/SocialStudies/Social Studies Book 6.jpg" class="secondary_image lazy" alt="Social Studies Book 6" /></span>
                                                </a>

                                            </div>
                                        </div>
                                        <div class="list-col8">
                                            <div class="product-content">
                                                <h3 class="product-title">
                                                    @Html.ActionLink("Download", "Download", "Admin", new { filepath = "~/Content/Downloadables/SocialStudies/Social Studies Book 6 New.pdf", filename = "Bookwise - Social Studies 6.pdf" }, null)

                                                </h3>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="first vgw-items col-md-2 col-xs-6 post-207 product type-product status-publish has-post-thumbnail product_cat-arts-photography product_cat-audiobooks product_cat-biographies product_cat-business-money product_cat-bussiness-money product_cat-calendars product_cat-casual-shirts product_cat-childrens-books product_cat-chinos product_cat-comics product_cat-computers product_cat-cookbooks product_cat-dress-pants product_cat-education product_cat-limited-edition product_cat-mens product_cat-womens product_tag-tag1 product_tag-tag2 product_tag-tag3 product_tag-tag4 instock sale featured taxable shipping-taxable purchasable product-type-simple">

                                    <div class="vgw-item effect-3">
                                        <div class="list-col4">

                                            <div class="product-image">
                                                <a title="Social Studies Book 7">
                                                    <img width="200" height="280" src="~/Content/Mockups/TeachersCorner/SocialStudies/Social Studies Book 6.jpg" class="primary_image lazy wp-post-image" alt="Social Studies Book 7" /><span class="second"><img width="200" height="280" src="~/Content/Mockups/TeachersCorner/SocialStudies/Social Studies Book 7.jpg" class="secondary_image lazy" alt="Social Studies Book 7" /></span>
                                                </a>

                                            </div>
                                        </div>
                                        <div class="list-col8">
                                            <div class="product-content">
                                                <h3 class="product-title">
                                                    @Html.ActionLink("Download", "Download", "Admin", new { filepath = "~/Content/Downloadables/SocialStudies/Social Studies Book 7 New.pdf", filename = "Bookwise - Social Studies 7.pdf" }, null)

                                                </h3>
                                            </div>
                                        </div>
                                    </div>

                                </div>



                                <div class="first vgw-items col-md-2 col-xs-6 post-207 product type-product status-publish has-post-thumbnail product_cat-arts-photography product_cat-audiobooks product_cat-biographies product_cat-business-money product_cat-bussiness-money product_cat-calendars product_cat-casual-shirts product_cat-childrens-books product_cat-chinos product_cat-comics product_cat-computers product_cat-cookbooks product_cat-dress-pants product_cat-education product_cat-limited-edition product_cat-mens product_cat-womens product_tag-tag1 product_tag-tag2 product_tag-tag3 product_tag-tag4 instock sale featured taxable shipping-taxable purchasable product-type-simple">

                                    <div class="vgw-item effect-3">
                                        <div class="list-col4">

                                            <div class="product-image">
                                                <a title="Social Studies Book 8">
                                                    <img width="200" height="280" src="~/Content/Mockups/TeachersCorner/SocialStudies/Social Studies Book 8.jpg" class="primary_image lazy wp-post-image" alt="Social Studies Book 8" /><span class="second"><img width="200" height="280" src="~/Content/Mockups/TeachersCorner/SocialStudies/Social Studies Book 8.jpg" class="secondary_image lazy" alt="Social Studies Book 8" /></span>
                                                </a>

                                            </div>
                                        </div>
                                        <div class="list-col8">
                                            <div class="product-content">
                                                <h3 class="product-title">
                                                    @Html.ActionLink("Download", "Download", "Admin", new { filepath = "~/Content/Downloadables/SocialStudies/Social Studies Book 8 New.pdf", filename = "Bookwise - Social Studies 8.pdf" }, null)

                                                </h3>
                                            </div>
                                        </div>
                                    </div>

                                </div>


                            </div>
                        </div>
                    </div>
                </div>

                <div class="pull-left wpb_column vc_column_container vc_col-sm-4 vc_col-lg-3 vc_col-md-4">
                    <div class="vc_column-inner ">
                        <div class="wpb_wrapper">
                            <div class="vc_row wpb_row vc_inner vc_row-fluid vc_custom_1490545088729">
                                <div class="wpb_column vc_column_container vc_col-sm-12">
                                    <div class="vc_column-inner ">
                                        <div class="wpb_wrapper">
                                            <div class="wpb_widgetised_column wpb_content_element">
                                                <div class="wpb_wrapper">

                                                    <aside id="vg_skybook_category_treeview-2" class="widget sidebar sidebar-shop widget_vg_skybook_category_treeview">
                                                        <div class="widget-title"><h3 class="wgtitle style-title">Categories</h3></div>
                                                        <div id="vgw-category-treeview_sidebar" class="vg-skybook-category-treeview ">
                                                            <ul class="level0 filetree">
                                                                <li class="0">
                                                                    <a href="/BySeries/ScienceWorld/"><span class="catTitle folder">Science World</span></a>
                                                                <li class="0">
                                                                    <a href="/BySeries/GrammarMore/"><span class="catTitle folder">Grammar & More</span></a>
                                                                </li>
                                                                <li class="0">
                                                                    <a href="/BySeries/RightClick/"><span class="catTitle folder">Right Click: My Book of Computers</span></a>
                                                                </li>
                                                                <li class="0">
                                                                    <a href="/BySeries/UrduLikhai/"><span class="catTitle folder">Urdu Likhai</span></a>
                                                                </li>
                                                                <li class="0">
                                                                    <a href="/BySeries/FunArt/"><span class="catTitle folder">Fun Art: Art & Craft Activity Books</span></a>
                                                                </li>
                                                                <li class="0">
                                                                    <a href="/BySeries/SocialStudies/"><span class="catTitle folder">Social Studies for Pakistan</span></a>
                                                                </li>
                                                                <li class="0">
                                                                    <a href="/BySeries/SecondarySocialStudies/"><span class="catTitle folder">Secondary Social Studies for Pakistan</span></a>
                                                                </li>
                                                                <li class="0">
                                                                    <a href="/BySeries/BeginnerSeries/"><span class="catTitle folder">Beginners Series</span></a>
                                                                </li>
                                                                <li class="0">
                                                                    <a href="/BySeries/LetsStartLearning/"><span class="catTitle folder">Let's Start Learning</span></a>
                                                                </li>
                                                                <li class="0">
                                                                    <a href="/BySeries/MyFunToLearnLanguage/"><span class="catTitle folder">My Fun-to-Learn Language</span></a>
                                                                </li>
                                                                <li class="0">
                                                                    <a href="/BySeries/MyFunToLearnMath/"><span class="catTitle folder">My Fun-to-Learn Maths</span></a>
                                                                </li>
                                                                <li class="0">
                                                                    <a href="/BySeries/UrduKiAmliKitab/"><span class="catTitle folder">Urdu Ki Amli Kitab</span></a>
                                                                </li>
                                                                <li class="0">
                                                                    <a href="/BySeries/AlhusnaIslamyat"><span class="catTitle folder">Alhusna Islamiyat</span></a>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                    </aside>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="vc_row-full-width vc_clearfix"></div>
        </article>
    </div>
</div>